### ISSUE TITLE
gravel 1 layer too low

### ISSUE THREAD

**Issue by BloodEko** [Barteks2x/173generator#15]
Hey.
I just tested the generator and saw that all the gravel is 1 layer too low, means there is 1 layer gravel missing.
Screenshot:  http://www.bilder-upload.eu/show.php?file=51717b-1501828447.png

**Comment by Barteks2x** [comment]
Have you compared it to vanilla beta 1.7.3 with the same seed?

**Comment by BloodEko** [comment]
In which plugin version do you want to me to test it ?

**Comment by Barteks2x** [comment]
Just test if Minecraft beta 1.7 generates it in similar way. I remember that it does, but I'm not entirely sure.

**Comment by BloodEko** [comment]
You are right, seems like the vanilla generator is also missing 1 layer.
So, is it not possible to change it in the plugin ?

**Comment by Barteks2x** [comment]
This is beyond what the plugin is supposed to do. And I stopped working on it long ago, so I will only fix "it doesn't work at all" bugs.

**Comment by Barteks2x** [comment]
It would be easy change once I had all the development environment set up. But I would also need to add config option for that, make automated tests I've added so far work with it, and all for a tiny change.

**Comment by BloodEko** [comment]
That a config option would be required and this would be probably more complicated than the feature by itself is also what i thought.
I can understand that the goal is to still provide the unmodified vanilla generator, because even some of the small flaws or unplaced blocks are a part of the atmosphere it creates.

It may be a tiny change, but can still have a impact, since it fixes that 'WTF went wrong here' thought every time someone walks near a gravel beach.
You should take a look at the difference between these 2 screenshots:

http://www.bilder-upload.eu/upload/d69848-1501894427.png
VS
http://www.bilder-upload.eu/upload/e5d39c-1501894415.png

Did you pause developing in general or do you mean importing all the stuff of this plugin to actually work with ?

**Comment by Barteks2x** [comment]
First, since the craftbukkit 1.7 and execially since the DMCA there is no simple way to run the plugin in dev environment from the IDE. The best I can do is set up BuildTools, wait forever for it to compile, and each time I want to test the plugin - copy the compiled version to plugins directory and run the server. This is much more cumbersome than what it used to be (just using "run" button in my IDE), and using debug mode is even more complicated. And I don't even use the same IDE I used to work on this plugin anymore. Getting it all  up and running again might take be at least a whole day before I can even start modifying the code. Without a config option it's one line change. But I'm not going to not add a config option for that. If you want a special version, you can modify and compile the code yourself. This is the line you need to change: https://github.com/Barteks2x/173generator/blob/a2466b4bef8c8f598509cb925f9cd651b27fdd02/src/main/java/com/github/barteks2x/b173gen/generator/ChunkProviderGenerate.java#L219 changing `AIR` to `GRAVEL`.

Second, craftbukkit is almost dead by now, and the replacement is Sponge. I was going to make similar plugin for sponge but I'm currently busy with [my other project](https://github.com/OpenCubicChunks/CubicChunks) and the Mixin feature I need for that isn't there yet.

And third, in the current state the plugin is unlikely to ever break in Craftbukkit/Spigot update, give the history of craftbukkit backwards compatibility. And it works fine and does what it's supposed to do.

**Comment by BloodEko** [comment]
Thanks for all the informations.
Crafbukkit is dead, but spigot is still running, which supports craftbukkit plugins to run ?
But yeah, seems like BuildTools got the new way to actually get the JARS, but how fast it is depends the used network ? for me 1 build process with BuildTools takes ~10min

I tried to build 173generator, but got some problems, here's the log: https://paste.md-5.net/bexobosave.xml

**Comment by Barteks2x** [comment]
Disable unit tests. I' ot exactly sure how to do it with maven but it has to be possible. Google it.

The tests expect terrain exactly like beta 1.7.3, but you modified it so they fail.

**Comment by BloodEko** [comment]
Found a option to disable that in my IDE.

Now it seems to have problems with the maven dependencies escpecially ProtocolLIB
here's the log: https://paste.md-5.net/miwuticofe.tex

**Comment by BloodEko** [comment]
Update:
I tested now the own builded version of the plugin, and it worked!

generated in default: http://www.bilder-upload.eu/show.php?file=857cca-1501962122.png
generated in own: http://www.bilder-upload.eu/show.php?file=5dfea5-1501962114.png

Just changing [this ](https://github.com/Barteks2x/173generator/blob/a2466b4bef8c8f598509cb925f9cd651b27fdd02/src/main/java/com/github/barteks2x/b173gen/generator/ChunkProviderGenerate.java#L219) ( as you assumed ) fixes the gravel beaches.

Thanks for the help, if I can do something for you let me know.

**Comment by BloodEko** [comment]
Hey,
i just got now the problem , that the bigtrees loose their leaves.
Is this common or could it caused by me compiling the JAR wrong ?

http://www.bilder-upload.eu/show.php?file=372667-1501966165.png

**Comment by Barteks2x** [comment]
This is a bug in the old big tree generator fixed only in some relatively recent version.

**Comment by BloodEko** [comment]
How can i apply thix fix to my version ?

**Comment by Barteks2x** [comment]
I'm not sure. I would need to look at the differences in code.

**Comment by BloodEko** [comment]
I made a pull with my version. That should show all differences ?

**Comment by Barteks2x** [comment]
Can you check if changng [this](https://github.com/Barteks2x/173generator/blob/a2466b4bef8c8f598509cb925f9cd651b27fdd02/src/main/java/com/github/barteks2x/b173gen/BukkitSimpleWorldImpl.java#L20) to
```java
    Block block = world.getBlockAt(x, y, z);
    block.setType(material);
    block.setData((byte)0);
```
fixes it?

This is my only idea, as nothing more really changed in this tree generator,

**Comment by BloodEko** [comment]
Seems to fix it. I made a pull, so you can add it easily.
How are the other changes in 131 affecting the generator ? Could it worth to use 131 instead of 130 ?

**Comment by Barteks2x** [comment]
The generator is (mostly?) unaffected, there may be some small performance difference, but hard to say which way it would go.

**Comment by BloodEko** [comment]
Hey. I just noticed another bug, big trees generated in this world lose a part of their leaves, when they get a block-update. After that the trees look like this: http://www.bilder-upload.eu/show.php?file=8ca41f-1503099472.png

Do you have an idea ?

**Comment by kurisubrooks** [comment]
@BloodEko create a new issue, don't comment new issues on old issues
